Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

ParameterLists:
  Max: 10

Style/ClassVars:
  Enabled: false
