sudo: false
os: linux
dist: trusty
language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
before_install:
  - gem install --no-document bundler -v '~> 1.16'
addons:
  apt:
    packages:
    - liblapack-dev
    - liblapacke-dev
